// Code generated by goctl. DO NOT EDIT.
// Source: home.proto

package homeclient

import (
	"context"
	"github.com/yanlihongaichila/home_type/home"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Bottom                  = home.Bottom
	MainBody                = home.MainBody
	Request                 = home.Request
	Response                = home.Response
	SearchBottomRequest     = home.SearchBottomRequest
	SearchBottomResponse    = home.SearchBottomResponse
	SearchMainBodyRequest   = home.SearchMainBodyRequest
	SearchMainBodyResponse  = home.SearchMainBodyResponse
	SearchSlideshowRequest  = home.SearchSlideshowRequest
	SearchSlideshowResponse = home.SearchSlideshowResponse
	SearchTopRequest        = home.SearchTopRequest
	SearchTopResponse       = home.SearchTopResponse
	Slideshow               = home.Slideshow
	TopInfo                 = home.TopInfo

	Home interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		SearchTop(ctx context.Context, in *SearchTopRequest, opts ...grpc.CallOption) (*SearchTopResponse, error)
		SearchSlideshow(ctx context.Context, in *SearchSlideshowRequest, opts ...grpc.CallOption) (*SearchSlideshowResponse, error)
		SearchMainBody(ctx context.Context, in *SearchMainBodyRequest, opts ...grpc.CallOption) (*SearchMainBodyResponse, error)
		SearchBottom(ctx context.Context, in *SearchBottomRequest, opts ...grpc.CallOption) (*SearchBottomResponse, error)
	}

	defaultHome struct {
		cli zrpc.Client
	}
)

func NewHome(cli zrpc.Client) Home {
	return &defaultHome{
		cli: cli,
	}
}

func (m *defaultHome) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultHome) SearchTop(ctx context.Context, in *SearchTopRequest, opts ...grpc.CallOption) (*SearchTopResponse, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.SearchTop(ctx, in, opts...)
}

func (m *defaultHome) SearchSlideshow(ctx context.Context, in *SearchSlideshowRequest, opts ...grpc.CallOption) (*SearchSlideshowResponse, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.SearchSlideshow(ctx, in, opts...)
}

func (m *defaultHome) SearchMainBody(ctx context.Context, in *SearchMainBodyRequest, opts ...grpc.CallOption) (*SearchMainBodyResponse, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.SearchMainBody(ctx, in, opts...)
}

func (m *defaultHome) SearchBottom(ctx context.Context, in *SearchBottomRequest, opts ...grpc.CallOption) (*SearchBottomResponse, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.SearchBottom(ctx, in, opts...)
}
